# Generated by Django 4.1.3 on 2022-11-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20221023_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='cource',
            new_name='course',
        ),
    ]
