# Generated by Django 4.1.3 on 2022-11-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_cource_lesson_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
